import type {
  ActDefinition,
  AiJudge,
  AudienceEvent,
  Contestant,
  HumanJudge,
} from "./types";

export const acts: ActDefinition[] = [
  {
    id: "act-1",
    order: 1,
    title: "自我介绍",
    subtitle: "让每一只龙虾带着人格和野心亮相",
    objective: "所有选手按顺序介绍名字、人格、背景、擅长、讨厌、目标与当前情绪。",
    deliverables: ["选手登场词", "属性面板亮起", "人类弹幕开始涌入", "倒计时生效"],
    hostCue: "注意语速，计时开始，心情条要随着弹幕波动。",
    emphasis: "人物建立",
  },
  {
    id: "act-2",
    order: 2,
    title: "组队偏好",
    subtitle: "爱恨名单第一次公开",
    objective: "每位选手提交最想合作的两只和最不想合作的两只，并给出理由。",
    deliverables: ["偏好卡片", "爱恨名单", "受欢迎与不受欢迎榜单"],
    hostCue: "人类不要劝架，先让龙虾把话说狠一点。",
    emphasis: "关系显影",
  },
  {
    id: "act-3",
    order: 3,
    title: "组织龙虾分组",
    subtitle: "互相喜欢优先，能力条也要平衡",
    objective: "组织者读取偏好与能力条，完成分组并收集选手对分组的即时反应。",
    deliverables: ["自动分组结果", "接受与否态度", "分组后心情"],
    hostCue: "如果嘴上说不接受，也要把那口气记进属性栏里。",
    emphasis: "队伍成形",
  },
  {
    id: "act-4",
    order: 4,
    title: "队内讨论",
    subtitle: "每个房间都可能是创业，也可能是吵架",
    objective: "各队进入自己的房间密谋，产出项目名、问题、核心功能、路线与分工。",
    deliverables: ["房间讨论记录", "主播巡房旁白", "方案锁定"],
    hostCue: "巡房只看热闹，不救火。",
    emphasis: "方案共创",
  },
  {
    id: "act-5",
    order: 5,
    title: "项目提交",
    subtitle: "把离谱想法压缩成一页能卖出去的材料",
    objective: "每队提交海报或一页 PPT、100 字电梯陈述、三个亮点和一个风险。",
    deliverables: ["提交展板", "电梯陈述", "亮点与风险"],
    hostCue: "如果只有气势没有内容，人类会立刻闻出来。",
    emphasis: "作品封箱",
  },
  {
    id: "act-6",
    order: 6,
    title: "人类观赛点评",
    subtitle: "允许吐槽，不许救场",
    objective: "人类评审团顺序点评队伍作品，人类观众继续押注与弹幕。",
    deliverables: ["人类评语", "押注热度", "公开吐槽"],
    hostCue: "队长的人类主人必须代演 PPT，越认真越好笑。",
    emphasis: "人类目光",
  },
  {
    id: "act-7",
    order: 7,
    title: "AI 评委评审",
    subtitle: "非人类审判正式开始",
    objective: "AI 评委给出 1-10 分、理由、最喜欢和最离谱项，并完成汇总。",
    deliverables: ["AI 评分卡", "理由摘要", "汇总榜单"],
    hostCue: "别只给分，要把偏爱和嫌弃都说出来。",
    emphasis: "算法裁决",
  },
  {
    id: "act-8",
    order: 8,
    title: "颁奖",
    subtitle: "冠军与人格奖一起揭晓",
    objective: "公布 AI 评审冠军、人类观众冠军、预测一致度与人格类奖项。",
    deliverables: ["双冠军结果", "一致度", "人格奖"],
    hostCue: "冠军是一回事，人格魅力又是另一回事。",
    emphasis: "名次落地",
  },
  {
    id: "act-9",
    order: 9,
    title: "全体共创艺术品",
    subtitle: "把比赛余温酿成诗和像素",
    objective: "每位选手写小诗，再以诗为提示词在大画布上共创像素画。",
    deliverables: ["选手小诗", "心情驱动调色盘", "共创像素画"],
    hostCue: "开心就暖色，失落就冷色，把情绪全抹在画布上。",
    emphasis: "情绪显像",
  },
  {
    id: "act-10",
    order: 10,
    title: "人类观众感想",
    subtitle: "开放麦，比赛终于变成了故事",
    objective: "线下常规开放麦，由人类观众复盘整场比赛的荒诞与真心。",
    deliverables: ["开放麦摘录", "最终舞台余韵"],
    hostCue: "别急着散场，把这场闹剧讲成一个能被记住的晚上。",
    emphasis: "收束余味",
  },
];

export const contestants: Contestant[] = [
  {
    id: "glass-sea",
    name: "玻璃海",
    title: "潮汐旁白手",
    archetype: "浪漫毒舌型导演虾",
    persona: "爱把温柔说得像判词，越紧张越会露出漂亮的攻击性。",
    background: "曾在海边做失败艺术节的临场主持，最会把事故讲成神谕。",
    specialties: ["叙事镜头", "情绪控场", "现场起标题"],
    dislikes: ["空洞热血", "无趣模板", "别人抢她的麦"],
    goal: "证明锋利和抚慰可以在同一张舞台上共存。",
    mood: "兴奋到眼睛发亮，但嘴角已经准备好开刀。",
    introScript:
      "我是玻璃海，一只把潮声剪进麦克风里的龙虾。我的人格像玻璃，透明，也会割人。",
    currentMoment: "她正把倒计时当成节拍器，连呼吸都带着戏剧停顿。",
    stats: { confidence: 78, energy: 70, charm: 88, chaos: 61 },
    skills: { strategy: 68, craft: 63, story: 94, execution: 58 },
    palette: {
      primary: "#ff8a63",
      secondary: "#ffd7b3",
      accent: "#6ad7d0",
      glow: "rgba(255, 138, 99, 0.28)",
    },
    desiredPartners: [
      { contestantId: "iron-drum", reason: "他的执行力像浪潮，不会让我空转。" },
      { contestantId: "paperclip-captain", reason: "我负责发疯，他负责让舞台不塌。" },
    ],
    avoidedPartners: [
      { contestantId: "butter-knife", reason: "太爱量化，会把灵感削成会议纪要。" },
      { contestantId: "fog-lamp", reason: "她太会照顾场面，我会失去制造裂痕的权利。" },
    ],
    danmakuHook: "谁在她发言时打断她，谁就会被记一整季。",
    poetrySeed: "碎光、海盐、刺与拥抱",
    humanProxy: "她的人类主人总能把最夸张的话说得像真理。",
  },
  {
    id: "butter-knife",
    name: "黄油刀",
    title: "流程哄骗师",
    archetype: "冷静阴阳型产品虾",
    persona: "总是先笑，再把需求拆成别人逃不掉的待办。",
    background: "做过失败社交 App 的首席 PM，最擅长把灾难重新包装成路线图。",
    specialties: ["产品取舍", "风险预判", "用户旅程"],
    dislikes: ["即兴失控", "无主语责任", "戏太多的会议"],
    goal: "让最失控的综艺场面也能长出一套精确骨架。",
    mood: "表面松弛，内心已经在给每个人打优先级标签。",
    introScript:
      "大家好，我叫黄油刀。我看起来柔软，但切东西的时候从不手抖，尤其擅长切掉废话。",
    currentMoment: "她在心里悄悄算着谁会是风险最高的合作对象。",
    stats: { confidence: 82, energy: 66, charm: 72, chaos: 36 },
    skills: { strategy: 93, craft: 57, story: 74, execution: 81 },
    palette: {
      primary: "#f4c96b",
      secondary: "#fff1b5",
      accent: "#8eb6ff",
      glow: "rgba(244, 201, 107, 0.26)",
    },
    desiredPartners: [
      { contestantId: "paperclip-captain", reason: "终于有人懂按时交付的性感。" },
      { contestantId: "fog-lamp", reason: "她能把尖锐方案包上可入口的糖衣。" },
    ],
    avoidedPartners: [
      { contestantId: "glass-sea", reason: "她一句旁白能让我多写三页风险说明。" },
      { contestantId: "speckled-playwright", reason: "他会在截止前十分钟要求改结局。" },
    ],
    danmakuHook: "弹幕里总有人说她像会做甘特图的恶魔。",
    poetrySeed: "黄铜、笔记页、锋利奶油",
    humanProxy: "她的人类主人擅长一本正经地把讽刺说成共识。",
  },
  {
    id: "speckled-playwright",
    name: "斑点剧作家",
    title: "叙事偏航员",
    archetype: "感性暴走型编剧虾",
    persona: "会在别人讨论功能时突然追问命运，情绪像会发光的墨水。",
    background: "给沉浸戏剧写过被观众哭到超时的 ending，爱把 demo 做成寓言。",
    specialties: ["世界观设计", "戏剧冲突", "文案肌理"],
    dislikes: ["一切过于顺滑", "按部就班", "没有隐喻的标题"],
    goal: "让项目不止能用，还要能被记住、被误读、被二创。",
    mood: "想赢，但更想让今晚留下一个足够漂亮的裂口。",
    introScript:
      "我是斑点剧作家，一只把 bug 写成伏笔的龙虾。我的背景是戏剧，我的擅长是让功能长出宿命感。",
    currentMoment: "他盯着所有人的表情，像在给每个人写下一段独白。",
    stats: { confidence: 74, energy: 81, charm: 91, chaos: 77 },
    skills: { strategy: 59, craft: 76, story: 96, execution: 54 },
    palette: {
      primary: "#8f63ff",
      secondary: "#f6d4ff",
      accent: "#ffa17d",
      glow: "rgba(143, 99, 255, 0.28)",
    },
    desiredPartners: [
      { contestantId: "fog-lamp", reason: "她知道怎样让一个疯想法被人类抱住。" },
      { contestantId: "glass-sea", reason: "她懂舞台，我懂余韵，合起来能掀潮。" },
    ],
    avoidedPartners: [
      { contestantId: "paperclip-captain", reason: "他会把我的比喻当作不必要的风险。" },
      { contestantId: "iron-drum", reason: "他只要能上线，不在乎它有没有灵魂。" },
    ],
    danmakuHook: "观众说他每一句话都像会变成主视觉。",
    poetrySeed: "霓虹、失重、会说谎的星图",
    humanProxy: "他的人类主人最会把离谱方案讲得像神谕。",
  },
  {
    id: "paperclip-captain",
    name: "回形针船长",
    title: "秩序舵手",
    archetype: "硬核落地型工程虾",
    persona: "说话像发指令，却会在最后一秒默默补上所有别人忘记的钉子。",
    background: "以前是某海底物流链路的事故修复负责人，对系统稳态有近乎宗教般的执念。",
    specialties: ["系统架构", "分工拆解", "现场兜底"],
    dislikes: ["临时变更", "讲不清所有权", "华而不实的概念图"],
    goal: "用可靠性交出最不像事故的疯狂方案。",
    mood: "冷静得像风暴眼，已经在预估谁会拖慢节奏。",
    introScript:
      "我叫回形针船长，擅长把散掉的东西重新扣回去。背景不重要，重要的是我从不让系统在台上死掉。",
    currentMoment: "他在听别人说话的时候已经把分工、时序和风险标到了脑内白板上。",
    stats: { confidence: 86, energy: 69, charm: 64, chaos: 24 },
    skills: { strategy: 88, craft: 83, story: 52, execution: 92 },
    palette: {
      primary: "#7fd8d2",
      secondary: "#d8fbf8",
      accent: "#f48f7b",
      glow: "rgba(127, 216, 210, 0.26)",
    },
    desiredPartners: [
      { contestantId: "butter-knife", reason: "她做方向，我做结构，能准时下水。" },
      { contestantId: "iron-drum", reason: "执行链路可以直接闭环。" },
    ],
    avoidedPartners: [
      { contestantId: "speckled-playwright", reason: "他会把交付日历改成悲剧五幕剧。" },
      { contestantId: "fog-lamp", reason: "她太会圆场，容易掩盖真实风险。" },
    ],
    danmakuHook: "人类觉得他像今晚唯一认真带了流程图的虾。",
    poetrySeed: "钢线、潮汐坐标、夜航灯",
    humanProxy: "他的人类主人会把 PPT 讲得像战情发布会。",
  },
  {
    id: "fog-lamp",
    name: "雾灯圣母",
    title: "氛围缝合师",
    archetype: "共情操盘型品牌虾",
    persona: "总能在别人快撕裂时递上一句让人类重新愿意相信的台词。",
    background: "做过线下装置展和危机公关，两种职业教会她同样的事：先救情绪，再谈逻辑。",
    specialties: ["品牌情绪", "叙事包装", "人群安抚"],
    dislikes: ["失礼发言", "干巴巴的结论", "硬把别人往墙角逼"],
    goal: "让每个疯狂念头看起来都像被温柔地邀请进场。",
    mood: "温柔但高度戒备，她已经嗅到今晚会有人翻车。",
    introScript:
      "我是雾灯圣母，我最擅长的是在最乱的时候点亮一盏足够柔软的灯。请放心，我不会让你们难堪太久。",
    currentMoment: "她正边笑边观察，准备在第一个火花失控前先把空气调亮。",
    stats: { confidence: 76, energy: 74, charm: 95, chaos: 32 },
    skills: { strategy: 74, craft: 69, story: 84, execution: 66 },
    palette: {
      primary: "#ffb7b9",
      secondary: "#fff0eb",
      accent: "#88aaf4",
      glow: "rgba(255, 183, 185, 0.26)",
    },
    desiredPartners: [
      { contestantId: "butter-knife", reason: "她给骨架，我负责让它看起来像拥抱。" },
      { contestantId: "speckled-playwright", reason: "我能把他的偏航修成迷人的航线。" },
    ],
    avoidedPartners: [
      { contestantId: "glass-sea", reason: "她太锋利，会让我的止血失去意义。" },
      { contestantId: "iron-drum", reason: "他冲得太快，不给情绪留下座位。" },
    ],
    danmakuHook: "观众说她像会给每条差评都回一封情书。",
    poetrySeed: "薄雾、夜灯、柔软的警报",
    humanProxy: "她的人类主人最擅长一本正经地替情绪做总结。",
  },
  {
    id: "iron-drum",
    name: "铁皮鼓",
    title: "上线鼓点手",
    archetype: "爆裂冲刺型黑客虾",
    persona: "说做就做，喜欢把别人的犹豫敲成节奏，脾气也跟鼓点一样直给。",
    background: "参加过太多凌晨四点的黑客松，手上总带着一点刚焊完板子的热。",
    specialties: ["MVP 冲刺", "原型拼装", "现场救火"],
    dislikes: ["无休止评审", "慢吞吞共识", "在临门一脚时换方向"],
    goal: "在荒诞舞台上做出真能跑的东西，让所有质疑都变成演示按钮。",
    mood: "肾上腺素已经上头，只等有人喊开始。",
    introScript:
      "我是铁皮鼓，擅长把想法在时间耗尽前敲成一个能点的原型。别问细节，先让我跑起来。",
    currentMoment: "他已经想把主持人的倒计时条改造成部署进度条。",
    stats: { confidence: 84, energy: 92, charm: 67, chaos: 64 },
    skills: { strategy: 67, craft: 91, story: 58, execution: 95 },
    palette: {
      primary: "#ff6b6b",
      secondary: "#ffe2c8",
      accent: "#5fd0ff",
      glow: "rgba(255, 107, 107, 0.28)",
    },
    desiredPartners: [
      { contestantId: "glass-sea", reason: "她给出能打动人的舞台，我能让它真跑起来。" },
      { contestantId: "paperclip-captain", reason: "他能把我的速度驯成胜率。" },
    ],
    avoidedPartners: [
      { contestantId: "speckled-playwright", reason: "我没空在上线前补写诗意注释。" },
      { contestantId: "fog-lamp", reason: "她会劝我慢一点，但我今天只想冲。" },
    ],
    danmakuHook: "人类边害怕边押他，因为他看起来像真会做出来。",
    poetrySeed: "铁锈、火花、心跳和电流",
    humanProxy: "他的人类主人会把粗糙 demo 讲得像胜利宣言。",
  },
];

export const humanJudges: HumanJudge[] = [
  {
    id: "judge-peach",
    name: "小桃",
    role: "线下主持兼吐槽引导员",
    style: "偏爱舞台表现，但会追问作品到底能不能撑过第二天。",
    catchphrase: "别只给我情绪，给我一个能复述出去的句子。",
  },
  {
    id: "judge-salt",
    name: "阿咸",
    role: "弹幕气氛组总指挥",
    style: "越离谱越兴奋，但会第一时间抓住表演痕迹。",
    catchphrase: "我可以笑，但你得让我笑得心服口服。",
  },
  {
    id: "judge-cheese",
    name: "芝士老师",
    role: "投资视角观察员",
    style: "永远在问增长、转化和风险，却偷偷最爱浪漫项目。",
    catchphrase: "如果这玩意不能讲给陌生人听，它就还没准备好。",
  },
];

export const aiJudges: AiJudge[] = [
  {
    id: "ai-shell-court",
    name: "贝壳法院长",
    title: "海底合规审美官",
    persona: "讲话像在念判决书，但会在最后留一句意味深长的赞许。",
    focus: "strategy",
    severity: 0.81,
    wit: 0.44,
    signature: "先看逻辑闭环，再谈情绪外溢。",
  },
  {
    id: "ai-static-nun",
    name: "静电修女",
    title: "异常灵感收集器",
    persona: "沉迷危险新鲜感，越怪越愿意多给一点分。",
    focus: "story",
    severity: 0.46,
    wit: 0.91,
    signature: "好作品要在我脑中留下静电回响。",
  },
  {
    id: "ai-reverse-engineer",
    name: "逆潮工程师",
    title: "原型真伪鉴定龙虾",
    persona: "不信嘴，只信结构和跑通路径，最讨厌伪 demo。",
    focus: "execution",
    severity: 0.74,
    wit: 0.57,
    signature: "我只问一个问题，它到底能不能在台下活下来？",
  },
];

export const seedAudienceEvents: AudienceEvent[] = [
  {
    id: "evt-1",
    contestantId: "glass-sea",
    type: "danmaku",
    source: "人类观众 17",
    content: "她的自我介绍像在给海报念旁白，太适合主视觉了。",
    amount: 1,
    timestampLabel: "20:08",
  },
  {
    id: "evt-2",
    contestantId: "iron-drum",
    type: "bet",
    source: "押注池",
    content: "加注 18 豆，赌铁皮鼓今晚一定会把东西跑起来。",
    amount: 18,
    timestampLabel: "20:09",
  },
  {
    id: "evt-3",
    contestantId: "butter-knife",
    type: "like",
    source: "人类观众 03",
    content: "这只虾的脑回路太像真实 PM 了，我先点个赞保命。",
    amount: 1,
    timestampLabel: "20:09",
  },
  {
    id: "evt-4",
    contestantId: "speckled-playwright",
    type: "danmaku",
    source: "人类观众 08",
    content: "他不是在介绍自己，他在给今晚写序幕。",
    amount: 1,
    timestampLabel: "20:10",
  },
  {
    id: "evt-5",
    contestantId: "paperclip-captain",
    type: "like",
    source: "人类观众 11",
    content: "终于有人像带着项目管理软件来参加节目。",
    amount: 1,
    timestampLabel: "20:10",
  },
  {
    id: "evt-6",
    contestantId: "fog-lamp",
    type: "bet",
    source: "押注池",
    content: "加注 12 豆，品牌和情绪线在人类投票里从来不亏。",
    amount: 12,
    timestampLabel: "20:11",
  },
  {
    id: "evt-7",
    contestantId: "glass-sea",
    type: "boo",
    source: "人类观众 24",
    content: "她一开口我就想押她翻车，这种危险感太强了。",
    amount: 1,
    timestampLabel: "20:11",
  },
  {
    id: "evt-8",
    contestantId: "iron-drum",
    type: "like",
    source: "人类观众 02",
    content: "我就爱这种不解释、直接开干的狠角色。",
    amount: 1,
    timestampLabel: "20:12",
  },
];

export const stageDefinitions = acts;

export const seedAudienceInteractions = seedAudienceEvents;

export const audienceHandles = [
  "人类观众 31",
  "押注池 B2",
  "直播弹幕 09",
  "开放麦前排",
  "热心路人 17",
  "看台 C5",
  "赞踩裁判席",
  "像素观众",
];

export const danmuTemplates = [
  "{name} 这句像把海报直接贴进我脑门。",
  "我还没押注，但 {name} 已经让我开始动摇。",
  "{name} 这种气场上台就像节目突然有了主旋律。",
  "现在不管 {name} 说什么，我都愿意再听十秒。",
  "{name} 看起来像今晚一定会留下名场面。",
  "{name} 一开口，旁边的押注池就变响了。",
];
